const ENGINE='PC-MOBILE-v2.0-alpha',DATA='2026-preseason-v1',STORE='powerCrunchAuditV2';
const $=id=>document.getElementById(id);const T=window.TEAMS.map(x=>({team:x[0],short:x[1],conference:window.CONFERENCE[x[1]]||'Unknown',overall:x[2],offense:x[3],defense:x[4],tempo:x[5],run:x[6]}));
let S=null,view='overall';
function rng(seed){let x=seed|0;return()=>((x=Math.imul(1664525,x)+1013904223|0)>>>0)/4294967296}
function norm(r){let u=1-r(),v=1-r();return Math.sqrt(-2*Math.log(u))*Math.cos(6.283185*v)}
function randomSeed(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]||1}
function winp(m,sd=21.5){return 1/(1+Math.exp(-m/(sd/1.7)))}
function ranks(field){return [...T].sort((a,b)=>b[field]-a[field]).map((t,i)=>({short:t.short,rank:i+1})).reduce((o,x)=>(o[x.short]=x.rank,o),{})}
const R={overall:ranks('overall'),offense:ranks('offense'),defense:ranks('defense')};
function human(field,t){const rank=R[field][t.short],score=Math.round(100*(T.length-rank)/(T.length-1));return Math.max(0,Math.min(100,score))}
function label(n){return n>=95?'National Elite':n>=90?'Elite':n>=80?'Excellent':n>=70?'Very Good':n>=60?'Above Average':n>=40?'Average':n>=30?'Below Average':n>=20?'Weak':n>=10?'Very Weak':'Bottom Tier'}
function matchup(a,h,n){let hfa=n?0:55,elo=h.overall+hfa-a.overall,off=(h.offense-a.defense+a.offense-h.defense)*.18,m=elo/25+off/25,total=54+((a.tempo+h.tempo)-1.04)*14;return{m,ap:total/2-m/2,hp:total/2+m/2,p:winp(m)}}
function projHTML(p,a,h,title){let fav=p.m>=0?h.team:a.team,by=Math.abs(p.m).toFixed(1),hp=(p.p*100).toFixed(1),ap=(100-p.p*100).toFixed(1);return`<div class="metric"><span>${title}</span><b>${fav} -${by}</b><div class="small">Projected: ${a.team} ${Math.max(0,Math.round(p.ap))}, ${h.team} ${Math.max(0,Math.round(p.hp))}</div><div class="bar"><i style="width:${ap}%"></i><i style="width:${hp}%"></i></div><div class="labels"><span>${a.short} ${ap}%</span><span>${h.short} ${hp}%</span></div></div>`}
function ratingCard(t){return`<div class="team-card"><h3>${t.team}</h3><div class="conf">${t.conference} · National #${R.overall[t.short]}</div>${['overall','offense','defense'].map(f=>{let n=human(f,t);return`<div class="rating-line"><span>${f[0].toUpperCase()+f.slice(1)}</span><b>${n}</b><em>${label(n)}</em></div>`}).join('')}<details><summary>Raw model ratings</summary><div class="raw">Overall ${t.overall.toFixed(2)} · Offense ${t.offense.toFixed(2)} · Defense ${t.defense.toFixed(2)}</div></details></div>`}
function fill(){for(const id of ['away','home'])$(id).innerHTML=T.map(t=>`<option>${t.team}</option>`).join('');$('away').value='Texas';$('home').value='Georgia';$('seed').value=randomSeed();const cs=['All',...new Set(T.map(t=>t.conference))];$('confFilter').innerHTML=cs.sort().map(c=>`<option>${c}</option>`).join('');renderRatings();renderHistory()}
function quarterPoints(team,opp,r,q){let edge=(team.offense-opp.defense)/180,base=6.5+edge+(team.tempo-.52)*5,lam=Math.max(1.5,base),x=Math.max(0,Math.round(lam+norm(r)*4.8)),vals=[0,3,6,7,10,13,14,17,20,21],best=vals.reduce((a,b)=>Math.abs(b-x)<Math.abs(a-x)?b:a);if(q===4&&r()<.08)best+=3;return best}
function scoreLabel(as,hs){if(as===hs)return`Tied ${as}-${hs}`;return as>hs?`${S.a.short} ${as}-${hs}`:`${S.h.short} ${hs}-${as}`}
function addQuarter(q){let teams=S.r()<.5?[S.a,S.h]:[S.h,S.a];for(const team of teams){const opp=team===S.a?S.h:S.a;const pts=quarterPoints(team,opp,S.r,q);if(team===S.a)S.aq[q-1]+=pts;else S.hq[q-1]+=pts;const as=sum(S.aq),hs=sum(S.hq),result=pts===0?(S.r()<.6?'Punt':'Turnover'):pts===3?'Field Goal':pts%7===0?'Touchdown':`${pts} points`;S.possessions.push({quarter:q,offense:team.team,short:team.short,result,points:pts,awayScore:as,homeScore:hs,score:scoreLabel(as,hs)});$('log').insertAdjacentHTML('afterbegin',`<div class="drive"><b>Q${q} · ${team.short}</b> · ${result} · <strong>${scoreLabel(as,hs)}</strong></div>`)} }
function start(){let a=T.find(t=>t.team===$('away').value),h=T.find(t=>t.team===$('home').value);if(a.team===h.team)return alert('Choose two different teams.');let seed=Number($('seed').value)||randomSeed(),n=$('neutral').checked;S={a,h,seed,n,r:rng(seed),q:0,aq:[0,0,0,0],hq:[0,0,0,0],ot:0,possessions:[],startedAt:new Date().toISOString(),saved:false};$('game').classList.remove('hidden');$('matchup').classList.remove('hidden');$('matchup').innerHTML=`<div class="matchup-grid">${ratingCard(a)}${ratingCard(h)}</div>`;$('an').textContent=a.short;$('hn').textContent=h.short;$('pregame').innerHTML=projHTML(matchup(a,h,n),a,h,'Pregame outlook');$('log').innerHTML='';render();window.scrollTo({top:$('matchup').offsetTop-8,behavior:'smooth'})}
function live(){let p=matchup(S.a,S.h,S.n),as=sum(S.aq),hs=sum(S.hq),rem=4-S.q,remaining=p.m*(rem/4),m=(hs-as)+remaining;p.m=m;p.ap=as+Math.max(0,(p.ap-as)*(rem/4));p.hp=hs+Math.max(0,(p.hp-hs)*(rem/4));p.p=winp(m,Math.max(8,21.5*Math.sqrt(Math.max(.08,rem/4))));return p}
function advance(){if(S.q<4){S.q++;addQuarter(S.q)}else if(sum(S.aq)===sum(S.hq)){S.ot++;let ap=3+(S.r()<.62?3:0)+(S.r()<.45?1:0),hp=3+(S.r()<.62?3:0)+(S.r()<.45?1:0);if(ap===hp)hp+=S.r()<.5?2:0;S.aq[3]+=ap;S.hq[3]+=hp;S.possessions.push({quarter:`OT${S.ot}`,offense:'Both',short:'OT',result:'Overtime',points:ap+hp,awayScore:sum(S.aq),homeScore:sum(S.hq),score:scoreLabel(sum(S.aq),sum(S.hq))});$('log').insertAdjacentHTML('afterbegin',`<div class="drive"><b>OT${S.ot}</b> · ${S.a.short} ${ap}, ${S.h.short} ${hp} · <strong>${scoreLabel(sum(S.aq),sum(S.hq))}</strong></div>`)}render()}
function sum(x){return x.reduce((a,b)=>a+(b||0),0)}
function finalNow(){return S&&S.q===4&&sum(S.aq)!==sum(S.hq)}
function audit(){return{simulationId:`PC-${Date.now()}-${S.seed}`,seed:S.seed,away:S.a.team,awayShort:S.a.short,home:S.h.team,homeShort:S.h.short,neutral:S.n,awayQuarters:[...S.aq],homeQuarters:[...S.hq],awayFinal:sum(S.aq),homeFinal:sum(S.hq),winner:sum(S.aq)>sum(S.hq)?S.a.team:S.h.team,possessions:S.possessions,pregame:matchup(S.a,S.h,S.n),completedAt:new Date().toISOString(),engineVersion:ENGINE,dataVersion:DATA}}
function getHistory(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
function saveAudit(){if(!S.saved&&finalNow()){let h=getHistory();h.unshift(audit());localStorage.setItem(STORE,JSON.stringify(h.slice(0,200)));S.saved=true;renderHistory()}}
function render(){for(let i=0;i<4;i++){$(`a${i+1}`).textContent=S.q>i?S.aq[i]:'-';$(`h${i+1}`).textContent=S.q>i?S.hq[i]:'-'}$('af').textContent=sum(S.aq);$('hf').textContent=sum(S.hq);let final=finalNow();$('live').innerHTML=final?`<div class="metric"><span>Final</span><b>${sum(S.aq)>sum(S.hq)?S.a.team:S.h.team} wins ${Math.max(sum(S.aq),sum(S.hq))}-${Math.min(sum(S.aq),sum(S.hq))}</b><div class="small">Seed ${S.seed} · Audit saved on this device</div></div>`:projHTML(live(),S.a,S.h,S.q?'Live projection':'Pregame');$('next').textContent=final?'Final':S.q<4?`Play Quarter ${S.q+1}`:`Play Overtime ${S.ot+1}`;$('next').disabled=final;saveAudit()}
function newGame(){const finished=finalNow();$('game').classList.add('hidden');$('matchup').classList.add('hidden');S=null;if(finished)$('seed').value=randomSeed();window.scrollTo({top:0,behavior:'smooth'})}
function renderRatings(){const conf=$('confFilter')?.value||'All';let list=T.filter(t=>conf==='All'||t.conference===conf).sort((a,b)=>b[view]-a[view]);const avg=list.reduce((s,t)=>s+human(view,t),0)/Math.max(1,list.length);$('ratingSummary').innerHTML=`<div class="summary"><b>${conf==='All'?'National Top 25':conf}</b><span>${list.length} teams · Avg ${view} ${avg.toFixed(1)}</span></div>`;$('ratingsTable').innerHTML=`<div class="rank-table">${list.slice(0,conf==='All'?25:list.length).map((t,i)=>`<div><b>${conf==='All'?R[view][t.short]:i+1}</b><span><strong>${t.team}</strong><small>${t.conference}</small></span><em>${human(view,t)}<small>${label(human(view,t))}</small></em></div>`).join('')}</div>`}
function renderHistory(){const q=($('historySearch')?.value||'').toLowerCase();const h=getHistory().filter(g=>!q||g.away.toLowerCase().includes(q)||g.home.toLowerCase().includes(q)||String(g.seed).includes(q));$('historyList').innerHTML=h.length?h.map((g,i)=>`<div class="history-item"><div><b>${g.awayShort} ${g.awayFinal} — ${g.homeShort} ${g.homeFinal}</b><span>${new Date(g.completedAt).toLocaleString()} · Seed ${g.seed}</span></div><button onclick="replayHistory(${i})" class="compact">Replay</button></div>`).join(''):'<p class="muted">No completed games saved on this device.</p>'}
window.replayHistory=i=>{const g=getHistory()[i];if(!g)return;$('away').value=g.away;$('home').value=g.home;$('seed').value=g.seed;$('neutral').checked=g.neutral;document.querySelector('[data-tab="game"]').click();start()}
function exportHistory(){const blob=new Blob([JSON.stringify(getHistory(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`power-crunch-audit-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`tab-${b.dataset.tab}`).classList.add('active');if(b.dataset.tab==='ratings')renderRatings();if(b.dataset.tab==='history')renderHistory()});
document.querySelectorAll('.seg button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.seg button').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;renderRatings()});
$('start').onclick=start;$('next').onclick=advance;$('newGame').onclick=newGame;$('randomSeed').onclick=()=>$('seed').value=randomSeed();$('confFilter').onchange=renderRatings;$('historySearch').oninput=renderHistory;$('exportHistory').onclick=exportHistory;$('clearHistory').onclick=()=>{if(confirm('Delete all saved game audits on this device?')){localStorage.removeItem(STORE);renderHistory()}};fill();if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});