const T=window.TEAMS.map(x=>({team:x[0],short:x[1],overall:x[2],offense:x[3],defense:x[4],tempo:x[5],run:x[6],uncertainty:(x[2]===1397.51?70:55)}));
const $=id=>document.getElementById(id);let S=null;
function h32(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let a=seed>>>0;return()=>{a|=0;a=a+0x6D2B79F5|0;let t=Math.imul(a^a>>>15,1|a);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function norm(r){let u=0,v=0;while(!u)u=r();while(!v)v=r();return Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}
function sum(a){return a.reduce((x,y)=>x+(y||0),0)}
function fill(){for(const id of['away','home'])$(id).innerHTML=T.map(t=>`<option>${t.team}</option>`).join('');$('away').value='Texas';$('home').value='Georgia';let d=new Date();$('seed').value=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`}
function alloc(total){let sh=[.23,.27,.23,.27],raw=sh.map(x=>total*x),q=raw.map(Math.floor);while(sum(q)<total){let best=raw.map((x,i)=>[x-q[i],i]).sort((a,b)=>b[0]-a[0])[0][1];q[best]++;raw[best]=q[best]}return q}
function setup(a,h,seed,n){let r=rng(seed),hfa=n?0:55;let ao=a.offense+norm(r)*a.uncertainty/2,ad=a.defense+norm(r)*a.uncertainty/2,ho=h.offense+hfa+norm(r)*h.uncertainty/2,hd=h.defense+hfa+norm(r)*h.uncertainty/2;let poss=Math.max(8,Math.min(17,Math.round(12+(a.tempo+h.tempo-1.04)*3+norm(r)*1.5)));return{a,h,seed,n,r,q:0,aq:[null,null,null,null],hq:[null,null,null,null],aot:[],hot:[],awayBall:r()<.5,drives:alloc(poss*2),ao,ad,ho,hd,log:[],status:'ready'}}
function drive(off,def,r,q,trailing){let d=(off.offense-def.defense)/400;let td=.245+d*.10+(off.tempo-.5)*.03,fg=.125+d*.025,to=.125-d*.02,punt=.405-d*.09,downs=.055;if(q===4&&trailing>=7){td+=.035;fg-=.015;to+=.02;punt-=.04}td=Math.max(.10,Math.min(.48,td));fg=Math.max(.06,Math.min(.20,fg));to=Math.max(.07,Math.min(.20,to));punt=Math.max(.20,Math.min(.58,punt));let arr=[['TD',td],['FG',fg],['TURNOVER',to],['PUNT',punt],['DOWNS',downs]],z=r()*arr.reduce((s,x)=>s+x[1],0),c=0;for(const[k,p]of arr){c+=p;if(z<=c)return k==='TD'?[k,r()<.955?7:6]:k==='FG'?[k,3]:[k,0]}return['PUNT',0]}
function ot(off,def,r,p){if(p>=3)return r()<(.458+(off.offense-def.defense)/3000)?2:0;let[x,pts]=drive(off,def,r,4,0);if(x==='TD')return p>=2?(r()<.458?8:6):(r()<.955?7:6);return pts}
function advance(s){if(s.status==='final')return;if(s.q<4){let qi=s.q,n=s.drives[qi];s.aq[qi]=0;s.hq[qi]=0;for(let i=0;i<n;i++){let as=sum(s.aq)+sum(s.aot),hs=sum(s.hq)+sum(s.hot),isA=s.awayBall,team=isA?s.a:s.h,opp=isA?s.h:s.a;let off={...team,offense:isA?s.ao:s.ho},def={...opp,defense:isA?s.hd:s.ad},tr=isA?Math.max(0,hs-as):Math.max(0,as-hs),[res,pts]=drive(off,def,s.r,qi+1,tr);if(isA)s.aq[qi]+=pts;else s.hq[qi]+=pts;s.log.push({q:qi+1,team:team.team,res,pts});s.awayBall=!s.awayBall}s.q++;let as=sum(s.aq)+sum(s.aot),hs=sum(s.hq)+sum(s.hot);s.status=s.q<4?'in_progress':as===hs?'overtime_ready':'final'}else{let p=s.aot.length+1,ap=ot(s.a,s.h,s.r,p),hp=ot(s.h,s.a,s.r,p);s.aot.push(ap);s.hot.push(hp);s.log.push({q:`OT${p}`,team:`${s.a.team}/${s.h.team}`,res:`${ap}-${hp}`,pts:''});s.status=ap===hp?'overtime_ready':'final'}}
function clone(s,seed){let c=JSON.parse(JSON.stringify({...s,r:null}));c.r=rng(seed);return c}
function full(a,h,seed,n){let s=setup(a,h,seed,n),guard=0;while(s.status!=='final'&&guard++<30)advance(s);return[sum(s.aq)+sum(s.aot),sum(s.hq)+sum(s.hot)]}
async function project(s,type){await new Promise(r=>setTimeout(r,20));let n=type==='pregame'?1200:600,as=[],hs=[],base=h32(`${s.seed}|${s.a.team}|${s.h.team}|${s.q}|${sum(s.aq)}|${sum(s.hq)}|${type}`);for(let i=0;i<n;i++){let sc;if(type==='pregame')sc=full(s.a,s.h,(base+i)>>>0,s.n);else{let c=clone(s,(base+i)>>>0),g=0;while(c.status!=='final'&&g++<30)advance(c);sc=[sum(c.aq)+sum(c.aot),sum(c.hq)+sum(c.hot)]}as.push(sc[0]);hs.push(sc[1])}let m=hs.map((x,i)=>x-as[i]),hp=m.filter(x=>x>0).length/n,mm=m.reduce((a,b)=>a+b,0)/n;return{fav:mm>=0?s.h.team:s.a.team,spread:Math.abs(mm),hp,ap:1-hp,as:sum(as)/n,hs:sum(hs)/n,n}}
function outlook(p,title){return`<div class="metric"><span>${title}</span><b>${p.fav} -${p.spread.toFixed(1)}</b><div class="small">Projected: ${S.a.team} ${p.as.toFixed(1)}, ${S.h.team} ${p.hs.toFixed(1)}</div><div class="bar"><i style="width:${p.ap*100}%"></i><i style="width:${p.hp*100}%"></i></div><div class="labels"><span>${S.a.team} ${(p.ap*100).toFixed(1)}%</span><span>${S.h.team} ${(p.hp*100).toFixed(1)}%</span></div></div>`}
function render(){for(let i=0;i<4;i++){let a=S.aq[i],h=S.hq[i];$(`a${i+1}`).textContent=a==null?'-':a;$(`h${i+1}`).textContent=h==null?'-':h}$('an').textContent=S.a.team;$('hn').textContent=S.h.team;$('af').textContent=sum(S.aq)+sum(S.aot);$('hf').textContent=sum(S.hq)+sum(S.hot);let final=S.status==='final';$('next').textContent=final?'Game Complete':S.q>=4?`Play Overtime ${S.aot.length+1}`:`Play Quarter ${S.q+1}`;$('next').disabled=final;$('log').innerHTML=S.log.length?S.log.slice(-24).reverse().map(x=>`<div class="drive"><b>${typeof x.q==='number'?'Q'+x.q:x.q}</b> · ${x.team} · ${x.res}${x.pts!==''?` · ${x.pts} pts`:''}</div>`).join(''):'No quarter has been played.'}
async function start(){let a=T.find(t=>t.team===$('away').value),h=T.find(t=>t.team===$('home').value);if(a.team===h.team)return alert('Choose two different teams.');$('start').disabled=true;$('start').textContent='Calculating pregame outlook…';S=setup(a,h,parseInt($('seed').value)||Date.now(),$('neutral').checked);let p=await project(S,'pregame');$('pregame').innerHTML=outlook(p,'Pregame outlook · 1,200 simulations');$('live').innerHTML='';$('game').classList.remove('hidden');render();$('start').disabled=false;$('start').textContent='Start Game';window.scrollTo({top:$('game').offsetTop-8,behavior:'smooth'})}
async function next(){if(!S||S.status==='final')return;$('next').disabled=true;$('next').textContent='Simulating…';advance(S);render();if(S.status==='final'){let as=sum(S.aq)+sum(S.aot),hs=sum(S.hq)+sum(S.hot),fav=as>hs?S.a.team:S.h.team;$('live').innerHTML=`<div class="metric"><span>Final</span><b>${fav} wins ${Math.max(as,hs)}-${Math.min(as,hs)}</b></div>`}else{let p=await project(S,'live');$('live').innerHTML=outlook(p,S.q===2?'Halftime live outlook · 600 continuations':`End Q${S.q} live outlook · 600 continuations`)}render()}
$('start').onclick=start;$('next').onclick=next;$('reset').onclick=()=>{$('game').classList.add('hidden');S=null};fill();