// POWER CRUNCH v2.0.2.2 environmental candidate overlay.
(function(){
const PRODUCT_VERSION='PC-MOBILE-v2.0.2.2',DATA_VERSION='2026-week2-eloK70-pscore04-env2022',C=window.PC_PSCORE_CONTROLS,P=window.PC_PROFILE_MAP;
const CFG={powerToMargin:80.0,homeField:2.2,neutralField:0.0,baseSigma:4.4,qWeights:[0.24,0.26,0.24,0.26],scoreValues:[0,3,6,7,10,13,14,17,20,21,24,27,28,31,34,35],precip:{none:{score:1,var:1,label:'None'},light:{score:.97,var:1.05,label:'Light'},moderate:{score:.93,var:1.12,label:'Moderate'},heavy:{score:.88,var:1.20,label:'Heavy'}}};
window.PC_ENGINE_VERSION=PRODUCT_VERSION;window.PC_DATA_VERSION=DATA_VERSION;window.PC_MODEL_NAME='EloK70 + calibrated margin + PSCORE shape + environmental state';window.PC_ENV_CONTROLS=CFG;
const E=id=>document.getElementById(id);
function envState(){let temp=Number(E('temperature')?.value);if(!Number.isFinite(temp))temp=70;temp=Math.max(-20,Math.min(130,temp));const precip=CFG.precip[E('precipitation')?.value]?E('precipitation').value:'none';return{temp,precip,even:!!E('evenTeams')?.checked};}
function tempFactors(temp){let common=1,road=1,variance=1;if(temp>85){const x=Math.min(30,temp-85);common*=1-x*.0020;variance*=1+x*.0040;}if(temp>95){const x=Math.min(20,temp-95);road*=1-x*.0030;}if(temp<40){const x=Math.min(40,40-temp);common*=1-x*.0025;variance*=1+x*.0030;}if(temp<20){const x=Math.min(20,20-temp);common*=1-x*.0025;}return{common,road,variance};}
function environment(){const s=envState(),t=tempFactors(s.temp),p=CFG.precip[s.precip];return{...s,awayEfficiency:t.common*t.road*p.score,homeEfficiency:t.common*p.score,variance:t.variance*p.var,precipLabel:p.label};}
function baseMatchup(a,h,n){const pa=P[a.short],ph=P[h.short],e=environment(),site=n?CFG.neutralField:CFG.homeField,powerGap=e.even?0:(ph.p-pa.p),m=powerGap*CFG.powerToMargin+site,tempoAdj=((a.tempo+h.tempo)-1.04)*14,m1Total=Math.max(C.baseTotal+tempoAdj,Math.abs(m)+2*C.minTeamScore),profileShift=ph.st+pa.st;let hp=(m1Total+m)/2+profileShift,ap=(m1Total-m)/2+profileShift;ap=Math.max(C.minTeamScore,ap*e.awayEfficiency);hp=Math.max(C.minTeamScore,hp*e.homeEfficiency);return{m:hp-ap,ap,hp,profileShift,tempoAdj,m1Total,site,powerGap,environment:e,staticMargin:m};}
const pmfCache=new Map(),remCache=new Map();
function footballPMF(target,sigma){const maxV=CFG.scoreValues[CFG.scoreValues.length-1],t=Math.max(0,Math.min(maxV,target)),key=t.toFixed(5)+'|'+sigma.toFixed(4);if(pmfCache.has(key))return pmfCache.get(key);if(t<=1e-10){const p=[[0,1]];pmfCache.set(key,p);return p;}if(t>=maxV-1e-10){const p=[[maxV,1]];pmfCache.set(key,p);return p;}let lo=-100,hi=140;for(let i=0;i<64;i++){const c=(lo+hi)/2;let z=0,mean=0;for(const v of CFG.scoreValues){const w=Math.exp(-0.5*Math.pow((v-c)/sigma,2));z+=w;mean+=v*w;}mean/=z;if(mean<t)lo=c;else hi=c;}const center=(lo+hi)/2;let z=0,raw=[];for(const v of CFG.scoreValues){const w=Math.exp(-0.5*Math.pow((v-center)/sigma,2));raw.push([v,w]);z+=w;}const out=raw.map(([v,w])=>[v,w/z]);pmfCache.set(key,out);return out;}
function samplePMF(pmf,r){let u=r(),cum=0;for(const [v,p] of pmf){cum+=p;if(u<=cum)return v;}return pmf[pmf.length-1][0];}
function convolve(a,b){const out=new Map();for(const [sa,pa] of a)for(const [sb,pb] of b)out.set(sa+sb,(out.get(sa+sb)||0)+pa*pb);return out;}
function remainingPMF(teamTarget,qDone,sigma){const key=teamTarget.toFixed(5)+'|'+qDone+'|'+sigma.toFixed(4);if(remCache.has(key))return remCache.get(key);let out=new Map([[0,1]]);for(let q=qDone;q<4;q++)out=convolve(out,new Map(footballPMF(teamTarget*CFG.qWeights[q],sigma)));remCache.set(key,out);return out;}
function homeWinProbability(ap,hp,qDone=0,as=0,hs=0,sigma=CFG.baseSigma){const A=remainingPMF(ap,qDone,sigma),H=remainingPMF(hp,qDone,sigma);let home=0,tie=0;for(const [a,pa] of A)for(const [h,ph] of H){const af=as+a,hf=hs+h,p=pa*ph;if(hf>af)home+=p;else if(hf===af)tie+=p;}return Math.max(0,Math.min(1,home+.5*tie));}
matchup=function(a,h,n){const b=baseMatchup(a,h,n),sigma=CFG.baseSigma*b.environment.variance;return{...b,p:homeWinProbability(b.ap,b.hp,0,0,0,sigma),sigma};};
quarterPoints=function(team,opp,r,q){const p=matchup(S.a,S.h,S.n),target=team.short===S.a.short?p.ap:p.hp,mean=Math.max(0,target*(CFG.qWeights[q-1]||.25));return samplePMF(footballPMF(mean,p.sigma),r);};
live=function(){const p=matchup(S.a,S.h,S.n),as=sum(S.aq),hs=sum(S.hq),qDone=S.q,remA=p.ap*CFG.qWeights.slice(qDone).reduce((x,y)=>x+y,0),remH=p.hp*CFG.qWeights.slice(qDone).reduce((x,y)=>x+y,0);return{...p,m:(hs-as)+(remH-remA),ap:as+remA,hp:hs+remH,p:homeWinProbability(p.ap,p.hp,qDone,as,hs,p.sigma)};};
const oldStart=start;start=function(){oldStart();if(S)S.environment={...environment()};};E('start').onclick=start;
const oldAudit=audit;audit=function(){const x=oldAudit(),p=matchup(S.a,S.h,S.n);x.engineVersion=PRODUCT_VERSION;x.dataVersion=DATA_VERSION;x.temperatureF=p.environment.temp;x.precipitation=p.environment.precip;x.evenTeams=p.environment.even;x.awayWeatherEfficiency=p.environment.awayEfficiency;x.homeWeatherEfficiency=p.environment.homeEfficiency;x.environmentVarianceMultiplier=p.environment.variance;x.staticMarginBeforeEnvironment=p.staticMargin;x.projectionPolicy='Calibrated Power margin + HFA, then environment alters team scoring efficiency/variance; no direct WP adjustment';x.evenTeamPolicy='Set Power gap to zero while preserving site and scoring-shape controls';return x;};
function note(){const e=environment(),el=E('environmentNote');if(el)el.textContent=`Environment: ${e.temp} F · ${e.precipLabel} precip · ${e.even?'Even-team ON':'Ratings ON'} · Away eff ${(e.awayEfficiency*100).toFixed(1)}% · Home eff ${(e.homeEfficiency*100).toFixed(1)}% · Variance x${e.variance.toFixed(2)}`;}
for(const id of ['temperature','precipitation','evenTeams'])E(id)?.addEventListener('change',note);note();
})();